---
- hosts: slave
  become: true
  remote_user: vagrant
  tasks:
  - name: cree repertoire
    file:
      path: ./prod_image
      state: directory
      mode: '0755'
  - name: cree fichier Dockerfile
    file:
      path: ./prod_image/Dockerfile
      state: touch
      mode: '0644'
  #- name: copier le .jar depuis .m2
    





  - name: ecrit dand Dockerfile
    blockinfile:
      path: ./prod_image/Dockerfile
      block: |
        FROM raphaelseguin/maven-git:latest
        COPY ./m2/*.jar
     

#  - name: fais un répertoire avec un Dockerfile d'apres un template
#    file:
    
#  - name: copier le build depuis .m2
#    copy:
#      src: .m2/*.jar
#      dest:

#  - name: build docker image

#  - name: push on docker hub

- hosts: prod
  become: yes
  remote_user: vagrant
  tasks:


#  - name: pull container
#    docker_image:
#      name: "{{ image }}"
#      src: pull    
#  - name: run container
#    docker_container:
#      name: "{{ image }}"
#      port: "80:80"
