---
- hosts: slave
  become: true
  remote_user: vagrant
  tasks:
  - name: cree repertoire
    file:
      path: ./prod_image
      state: directory
      mode: '0755'
  - name: cree fichier Dockerfile
    file:
      path: ./prod_image/Dockerfile
      state: touch
      mode: '0644'
  - name: ecrit Dockerfile
    blockinfile:
      path: ./prod_image/Dockerfile
      block: |
        COPY /home/vagrant/.m2/repository/com/gtm/devops/1.0/devops-1.0.war .
        EXPOSE 80
        ENTRYPOINT ['java']
        CMD ['-jar','devops-1.0.war']
  - name: install python docker lib
    pip:
      name: docker
      state: latest
  - name: build image docker
    docker_image:
      build: 
        path: ./prod_image
      name: devopsapp
      source: build
      pull: yes   
 
  - name: push to docker hub
    docker_image:
      name: devopsapp
      repository: raphaelseguin/devopsapp
      push: yes
      source: local

- hosts: prod
  become: yes
  remote_user: vagrant
  tasks:


#  - name: pull container
#    docker_image:
#      name: raphaelseguin/devopsapp
#      src: pull    
#  - name: run container
#    docker_container:
#      name: "{{ image }}"
#      port: "80:80"
