---
#tasks file for DOCKER_ROLE
- name: Ensure old versions of Docker are not installed.
  package:
    name: '{{ item }}'
    state: absent
  with_items: '{{ liste }}'

- name: Install yum-utils
  shell: 'sudo yum -y install yum-utils device-mapper-persistent-data lvm2'

- name: set up stable repository
  shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install DOCKER docker-engine
  shell: 'sudo yum -y install docker-ce docker-ce-cli containerd.io'
  notify: start docker

- name: Specify the port
  lineinfile:
    path: /usr/lib/systemd/system/docker.service
    regexp: '^ExecStart='
    insertafter: 'fd:// '
    line: ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:'{{ var_port }}' --containerd=/run/containerd/containerd.sock

